### PR TITLE
Add option for making all warnings into errors

### PR DESCRIPTION
**Pull request by sudarkoff**
- Add option `--error` that makes all warnings into errors
- Prefix output with either `Warning` or `Error`
- Return 1 if deprecated packages are detected and `--error` is passed
- Print to stderr

Very simple logic for now, no separation of warnings vs. errors on a per-requirement basis.

### CODE REVIEW

**Comment by sudarkoff** [comment]
I'll fix the tests tomorrow if the direction of this PR seems right.

**Comment by aconrad** [comment]
Thanks @sudarkoff, this is something I was planning on working today.

I want the default to exit with zero when everything is fine.

```
$ pip freeze | defrost reqs.yml
echo $?
0
```

If packages are found as deprecated, return 1.

```
$ pip freeze | defrost reqs.yml
Package(foo==0.1) does not satisfy Requirement(foo>=1.0): please upgrade!
echo $?
1
```

If users don't want to error code, they can provide `--exit-zero` option or something. There are also other flags I would like to introduce, such as `--missing` so it can fail if a package listed in a requirement are missing from the pip freeze then error out; the default behavior is to ignore missing packages.

**Comment by sudarkoff** [comment]
@aconrad I think of this tool as a sort of a linter. In that context, I think it would be extremely useful to have requirements that just warn in addition to requirements that generate an error. And for requirements that just warn I think returning `0` is more appropriate because by default you do not want to fail a build because of a warning. But at the same time, it is common for tools like this to have a flag that makes all warnings into errors (e.g.: `gcc --Werror`) if one wanted to perform a more strict check.

**Comment by aconrad** [comment]
All the linters I know return a non-zero exit status if additional clean up is necessary. It's also usual that the default behavior can be tweaked to ignore some errors.

For now in defrost there is no such concept of warning vs. error, it's more about pass vs. fail, so maybe this is too early for such change? Given the current state of defrost, I was planning on implementing an intermediate step and do what linters do, exit status of 1 when unsatisfied requirements are found. But maybe we should go right ahead and introduce the notion of warning vs. error... ?

**Comment by sudarkoff** [comment]
You're right, it doesn't make sense to talk about return codes until there's an actual notion of warnings vs. errors. Let's start there.

**Pull request closed without merging**
